config/routes.rb
Reciplease::Application.routes.draw do
  
  ## Override default devise functions with registration controller
  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  match "/users/reactivation" => "users#reactivation", :as => :reactivation
  match "/users/reactivate" => "users#reactivate", :as => :reactivate
  resources :users, :only => [:show]

  resources :recipes
  match "/recipes/:id/personalize" => "recipes#personalize", :as => :personalize_recipe
  match "/recipes/:id/history" => "recipes#history", :as => :recipe_history
  
  resources :comments

  resources :ratings, :only => [:create, :update, :destroy]
  
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#welcome"
  
  match "/gettingStarted" => "home#gettingStarted", :as => :gettingStarted
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  
  attr_accessible :body, :commentable_type, :commentable_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @comments = Comment.all
    @comment = Comment.new
  end
  
  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(params[:comment])
    if(current_user == nil)
      flash[:alert] = "You must be logged in to comment"
      return_to_commentable(@comment);
    elsif(@comment.body == "")
      flash[:alert] = "You cannot post an empty comment"
      return_to_commentable(@comment);
    else
      @comment.user_id = current_user.id
      if @comment.save
        return_to_commentable(@comment);
      else
        flash[:alert] = "Comment failed to save, please try again!"
      end
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update 
    @comment = Comment.find(params[:id])
    @comment.update_attributes(params[:comment])
      
    if @comment.save
      flash[:notice] = "Comment Updated!"
      return_to_commentable(@comment)
    else
      flash[:alert] = "Comment failed to save, please try again!"
     end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    return_to_commentable(@comment);
  end
  
  def return_to_commentable(comment)
    redirect_to :controller => comment.commentable_type, :action => 'show', :id => comment.commentable_id
  end
  
end

app/helpers/comment_helper.rb
module CommentHelper

  def fetch_comments(type, id)
    # Fetch the ten most recent comments and put them in order by most recent
    comments = Comment.where(:commentable_type => type, :commentable_id => id)
    paginated_comments = comments.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end
  
end

app/views/comments/_display_comments.html.erb
<h3> Comment </h3>

<!-- Comment Form -->
<%= form_for :comment, :url => { :action => 'create', :controller => 'comments' } do |f|%>

  <%= f.text_area(:body, :style => 'width:100%', :rows => 8) %> <br />
  <p align="right"><%= f.submit ' Submit ' %></p>

  <%= f.hidden_field :commentable_type, :value => params[:controller] %>
  <%= f.hidden_field :commentable_id, :value => params[:id] %>
<% end %>

<!-- Comment Display -->
<% comments = fetch_comments(params[:controller], params[:id]) %>

<% comments.each do |c| %>
	<% user = User.find(c.user_id) %>
	<div class="comment">
		<%= link_to(image_tag(user.gravatar_url, :size => '50x50'), user_path(user)) %>
		<span class="comment_author">
			<%= link_to(user.name, user_path(user)) %>
		</span> 
		<% if(current_user != nil && c.user_id == current_user.id) %>
			<span class="comment_options">
				<%= link_to raw('<i class="icon-edit"></i>'), edit_comment_path(c) %> 
				<%= link_to raw('<i class="icon-remove-sign"></i>'), comment_path(c) , :confirm => "Are you sure?", :method => :delete %>
			</span>
		<% end %>
		<br />
		<span class = "comment_body">
			<%= render_markdown(c.body) %>
		</span>
	</div>
<% end %>

<span class = "apple_pagination">
	<%= will_paginate comments %>
</span>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_for @comment, :url => { :action => "update", :controller => 'comments' } do |f| %>
  <%= f.text_area :body, :required => true, :style => 'width:50%', :rows => 8 %> <br/>
  <%= f.submit ' Submit ' =%>
<% end %>

<%= link_to_function "Back", "history.back()" %>