config/routes.rb
Reciplease::Application.routes.draw do
  
  ## Override default devise functions with registration controller
  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  match "/users/reactivation" => "users#reactivation", :as => :reactivation
  match "/users/reactivate" => "users#reactivate", :as => :reactivate
  resources :users, :only => [:show]

  resources :recipes
  match "/recipes/:id/personalize" => "recipes#personalize", :as => :personalize_recipe
  match "/recipes/:id/history" => "recipes#history", :as => :recipe_history
  
  resources :comments

  resources :ratings, :only => [:create, :update, :destroy]
  
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#welcome"
  
  match "/gettingStarted" => "home#gettingStarted", :as => :gettingStarted
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  acts_as_commentable
  
  belongs_to :owner, :class_name => "User"
  has_many :ratings
  belongs_to :parent, :class_name => "Recipe"
  has_many :forks, :class_name => "Recipe", :foreign_key => "parent_id"

  validates_presence_of :name, :owner, :ingredients, :description, :instructions
  attr_accessible :name, :owner_id, :description, :instructions, :forks, :ingredients, :image, :parent_id
  
   has_attached_file :image, styles: {
    thumb: '100x100',
    square: '200x200',
    medium: '300x300'
  }
  
  def average_rating
    @score = 0
    self.ratings.each do |rating|
        @score = @score + rating.score
    end
    @count = self.ratings.size
    return @score.to_f / @count.to_f
  end
  
  def self.api_rep
    Recipe.order("name ASC").all.map do |recipe|
      recipe.api_hash
    end
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
  
  def api_hash
    {
      id: self.id, name: self.name, description: self.description, instructions: self.instructions, owner_id: self.owner_id, parent_id: self.parent_id, picture: self.image
    }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.search(params[:search])
    @top_recipes = nil
    respond_to do |format|
      format.html # index.html.erb
      format.json do
        render json: Recipe.api_rep
      end
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    if @recipe.owner.active and @recipe != nil
      respond_to do |format|
        format.html # show.html.erb
        format.json do
          render json: @recipe.api_hash
        end
      end
    else
      flash[:notice] = "Recipe no longer exists!"
      redirect_to recipes_path
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    is_logged_in = current_user != nil
    respond_to do |format|
      if is_logged_in
        format.html # new.html.erb
      else
        format.html { redirect_to recipes_url, alert: "You need to login to create recipes." }
      end
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    is_logged_in = current_user != nil
    is_owner = @recipe.owner == current_user
    if not is_logged_in
      redirect_to @recipe, alert: "You need to login to edit recipes."
    elsif not is_owner
      redirect_to @recipe, alert: "You do not have permission to edit this recipe."
    end
  end
  
  # GET /recipes/1/personalize
  def personalize
    @recipe = Recipe.find(params[:id]).dup
    @recipe.parent_id = params[:id];
    is_logged_in = current_user != nil
    is_owner = Recipe.find(params[:id]).owner == current_user
    respond_to do |format|
      if is_logged_in
        format.html # personalize.html.erb
      else
        format.html { redirect_to recipe_path(@recipe.parent_id), alert: "You need to login to personalize recipes." }
      end
      if is_owner
        format.html { redirect_to edit_recipe_path }
      end
    end
  end

  # POST /recipes
  # POST /recipes.json 
  def create
    is_logged_in = current_user != nil
    @recipe_fields = params[:recipe]
    if is_logged_in
      @recipe_fields[:owner_id] = current_user.id
    end
    @recipe = Recipe.new(@recipe_fields)
    respond_to do |format|
      if not is_logged_in
        format.html { render action: "new", alert: "You need to login to create recipes.", status: :unauthorized }
        format.json { render json: @recipe.errors, status: :unauthorized }
      elsif @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    is_logged_in = current_user != nil
    is_owner = @recipe.owner == current_user
    respond_to do |format|
      if not is_logged_in
        format.html { render action: "show", alert: "You need to login to edit recipes.", status: :unauthorized }
        format.json { render json: @recipe.errors, status: :unauthorized }
      elsif not is_owner
        format.html { render action: "show", alert: "You do not have permission to edit this recipe.", status: :forbidden }
        format.json { render json: @recipe.errors, status: :forbidden }
      elsif @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])   
    is_logged_in = current_user != nil
    is_owner = @recipe.owner == current_user
    if is_logged_in and is_owner
      children = Recipe.where(:parent_id => params[:id])
      children.each do |child|
        child.update_attribute(:parent_id, @recipe.parent_id)
        child.save
      end
      Rating.where(:recipe_id => params[:id]).each do |rating|
        rating.destroy
      end
      @recipe.destroy
    end  
    respond_to do |format|
      if not is_logged_in
        format.html { redirect_to @recipe, alert: "You need to login to delete recipes." }
        format.json { head :no_content, status: :unauthorized }
      elsif not is_owner
        format.html { redirect_to @recipe, alert: "You do not have permission to delete this recipe." }
        format.json { head :no_content, status: :forbidden }
      else
        # Success
        format.html { redirect_to recipes_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  # Return's the current user's rating object for the current recipe
  # Or returns a new rating object
  def rating_ballot
    if user_signed_in?
      if @rating = current_user.ratings.find_by_recipe_id(params[:id])
        @rating
      else
        current_user.ratings.new
      end
    else # not signed in
      Rating.new
    end
  end

  def current_user_rating
    if user_signed_in? and @rating = current_user.ratings.find_by_recipe_id(params[:id])
      @rating.score
    else
      "N/A"
    end
  end
  
end

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, :url => { :action => action }, :html => {:class => "nifty_form"} do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.input :name, :label => 'Recipe name' %>
	<%= f.label :Description %>
	<%= f.text_area :description, :required => false, :cols => 30, :rows => 5 %>
	<%= f.label :Ingredients %>
	<%= f.text_area :ingredients, :required => false, :cols => 30, :rows => 5 %>
	<%= f.hidden_field :parent_id, :required => false %>
	<%= f.label :instructions, :required => true %>
	<%= f.text_area :instructions, :cols => 30, :rows => 5 %>

	<div class="field">
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>
  </div>
  
  <br />
  <% if defined?(submit_label) %>
  	<%= f.button :submit, submit_label %>
  <% else %>
  	<%= f.button :submit %>
  <% end %>
<% end %>

app/views/recipes/_rating_form.html.erb
<% content_for(:scripts) do %>
<%= javascript_include_tag 'rating_ballot' %>
<% end %>

<%= form_for(rating_ballot, :remote => true, :html => { :class => 'rating_ballot' }) do |f| %>
<% [1,2,3,4,5].each do |n| %>
<%= f.label("score_"+n.to_s, content_tag(:span, n.to_s), {:class=>"rating", :id=>n}) %>
<%= radio_button_tag("rating[score]", n, current_user_rating == n, :class => 'rating_button') %>
<% end %>

<%= hidden_field_tag("recipe_id", @recipe.id) %>
<%#= f.button :submit, {:id => 'rating_submit'} %>

<% end %>

app/views/recipes/_thumbnail_block.html.erb
<li class="span3">
  <div class="thumbnail" style="height: 350px">
    <%= link_to image_tag(recipe.image.url(:square), :border=>0, :alt=>'recipe thumbnail', :title=>''),
         recipe, :class=>"thumbnail" %>
    
    <h3 style="display:inline"><%= recipe.name %></h3>
    <p style="display:inline">by <%= link_to recipe.owner.name, recipe.owner, :style=>"text-decoration: none" %></p>

	<div style="word-wrap: break-word;">
    <p><%= truncate recipe.description, length: 100 %></p>
    </div>
    
    <% if recipe.owner == current_user %>
      <%= link_to 'Edit', edit_recipe_path(recipe), :style=>"text-decoration: none" %>
      <%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete, :style=>"text-decoration: none" %>
    <% end %>
  </div>
</li>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render :partial => "form", :locals => { :action => "update" } %>

<%= link_to 'Cancel', recipes_path %>

app/views/recipes/history.html.erb
<div class="row">
  <div class="span3"><h1>Recipe history</h1></div>
</div>
<div class="row-fluid">
	<% recipe  = Recipe.find(params[:id]) %>
	<% history = [] %>
	<% i = 0 %>

	<% while recipe.parent != nil %>
		<% parent = Recipe.find(recipe.parent) %>
		<% if parent.owner.active %>
			<% history << parent %>
		<% end %>
		<% recipe = recipe.parent %>
    <% end %>
    
    <!-- TODO: Add some nice connections betwen recipes -->
    <% history.reverse.each do |r| %>
    	<%= render "recipes/thumbnail_block", :recipe => r %>
    <% end %>
  </ul>
</div>

app/views/recipes/index.html.erb
<div class="row">
  <div class="span5"><h1>Listing recipes</h1></div>
  <div class="span5"></div>
  <div class="span2"><%= link_to 'New Recipe', new_recipe_path, :class=>"btn btn-success" %></div>
</div>
<div class="row-fluid">
  <ul class="thumbnails">
  	
    <% paginated_recipes = @recipes.paginate(:page => params[:page], :per_page => 12) %>
    <% paginated_recipes.each do |recipe| %>
      <% if recipe.owner.active %>
      	<%= render "recipes/thumbnail_block", :recipe => recipe %>
      <% end%>
    <% end %>
  </ul>
</div>

<span class = "apple_pagination">
	<%= will_paginate paginated_recipes %>
</span>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render :partial => "form", :locals => { :action => "create" } %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/personalize.html.erb
<h1>Personalizing recipe</h1>

<%= render :partial => "form", :locals => { :action => "create", :submit_label => "Personalize" } %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="row">
	<div class="span7">
		<h2><%= @recipe.name %></h2>
		<h4>By <%= link_to @recipe.owner.name, @recipe.owner %></h4>
				
		<%= render "rating_form" %><br />
		
		<h5>Description</h5>
		<p><%= render_markdown(@recipe.description) %></p>
		
		<h5>Ingredients</h5>
		<p><%= render_markdown(@recipe.ingredients) %></p>
		
		<h5>Instructions</h5>
		<p><%= render_markdown(@recipe.instructions)  %></p>
		
		<br />
		<%= social_share_button_tag("Check out this awesome recipe!\n\n#{@recipe.name}") %>
		<br />
		
		<% if @recipe.owner == current_user %>
		  <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
		  <%= link_to 'Delete', recipe_path(@recipe), :method => :delete %> |
		<% else %>
		  <%= link_to 'Personalize', personalize_recipe_path(@recipe) %> |
		<% end %>
		<%= link_to 'History', recipe_history_path(@recipe) %>
	</div>
	
	<div id="image" class="span5" style="float:right">
	  <%= image_tag @recipe.image.url(:medium) %>
	</div>
</div>
	
<div class="row spacer">
	<div class = "span7">
		<%= render 'comments/display_comments'%>
		<%= yield %>
	</div>
</div>