config/routes.rb
Reciplease::Application.routes.draw do
  
  ## Override default devise functions with registration controller
  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  match "/users/reactivation" => "users#reactivation", :as => :reactivation
  match "/users/reactivate" => "users#reactivate", :as => :reactivate
  resources :users, :only => [:show]

  resources :recipes
  match "/recipes/:id/personalize" => "recipes#personalize", :as => :personalize_recipe
  match "/recipes/:id/history" => "recipes#history", :as => :recipe_history
  
  resources :comments

  resources :ratings, :only => [:create, :update, :destroy]
  
  authenticated :user do
    root :to => 'home#home'
  end
  root :to => "home#welcome"
  
  match "/gettingStarted" => "home#gettingStarted", :as => :gettingStarted
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    # TODO: Should we remove this? Maybe just redirect to the current_user page
    # respond_to do |format|
     # format.html # index.html.erb
     # format.json do
      #  render json: User.api_rep
     # end
    #end
  end
end

app/views/home/gettingStarted.html.erb
<h2> Getting Started </h2>

<p>
	Welcome to Reciplease! This guide is intended to help you setup your account and make your very first contribution.
</p>

<h4> Creating an Account </h4>

<p>
	The first step to using Reciplease is creating an account. If you have already done this, welcome! You can skip this step.
</p>

<blockquote>
	<li>Click the <%= link_to 'Join Us!', new_user_registration_path %> button on the home page </li>
	<li>Enter your registration info </li>
	<li>A name, email address, and password are required to create an account </li>
	<li>Click "Sign Up" </li>
	<li>A confirmation email will be sent to the provided email </li>
	<li>Open your cofirmation email and click "Confirm my account" </li>
</blockquote>

<h4>Editing your Account </h4>

<p>
	Now you can navigate to your profile and make edits to add any additional information you would like to share. 
	By clicking your name in the top right corner, you can go to your profile page. 
	Here you will find an edit account button. This is also where you will go if you want to remove your account
	(we hope you won’t!). 
</p>

<p>
	Your profile image uses the <%= link_to 'Gravatar', "http://gravatar.com" %> service. Currently, You need to create an account there if you want
	to customize it.
</p>

<h4>Browsing Recipes</h4>

<p>
	Now that you’re logged in, there’s an <%= link_to 'All Recipes', recipes_path %> link on the homepage. 
	From the main recipe list, you can access all of the recipes on the site. 
	You can also search for specific recipes using the search bar.
</p>	
	
<h4>Commenting and Rating</h4>

<p>
	You can comment on recipes by using the comment box at the bottom of the page,
	you can rate a recipe by clicking on the stars near the top of the page. 
	A 5-star recipe will be added to your favorites on your profile. 
	Please be kind, not everyone can be as awesome as you!
</p>

<p>
	Commenting and recipe descriptions support <%= link_to 'Markdown', 'http://en.wikipedia.org/wiki/Markdown' %>,
	so you can add some pizazz to your text.
</p>

<h4>Creating your own Recipes</h4>

<p>
	On the recipe list, you can click New Recipe to create a recipe. 
	You will then enter instructions and a description of the dish
</p>

<h4>Personalizing a Recipe</h4>

<p>
	While viewing a recipe from another user, you can click personalize. 
	Upon doing so, you are presented with an edit recipe form. 
	Any edit you make will be saved to your own version of the recipe.
</p>

<h4>History</h4>

<p>
	When you view your recipe or any other recipe that was based off of another recipe, 
	you can click history to see the older versions of the recipe.
</p>

app/views/home/home.html.erb
<div class="container">
	<div class="page-header">
  		<h1>Reciplease Dashboard</h1>
	</div>
	<div class="row">
  		<div class="span4">
  			<ul class="thumbnails">
  				<li class="span4">
    				<%= link_to image_tag("dashboard/profile.png"), user_path(current_user), :class=>"thumbnail" %>
  				</li>
			</ul>
		</div>
  		<div class="span4">
  			<ul class="thumbnails">
  				<li class="span4">
      				<%= link_to image_tag("dashboard/new_recipe.png"), new_recipe_path, :class=>"thumbnail" %>
  				</li>
			</ul>
		</div>
  		<div class="span4">
  			<ul class="thumbnails">
  				<li class="span4">
      				<%= link_to image_tag("dashboard/all_recipes.png"), recipes_path, :class=>"thumbnail" %>
  				</li>
			</ul>
		</div>
	</div>
	
	<div class="row" align="center">
		<%= link_to('Getting Started!', gettingStarted_path , :class => "btn btn-large btn-primary")%>
	</div>
</div>

app/views/home/welcome.html.erb
<div class="container-narrow" style="margin: 0 auto; max-width: 700px">
	<div class="jumbotron" style="text-align: center">
		<h1 style="text-align: center">Welcome to the<br>Reciplease Development site!</h1>
		<p class="lead">
			The Reciplease Project is an attempt to bring the fun of cooking to a wider audience. There are plenty of websites that provide recipes, but not many that help you make recipes your own. That's the goal of Reciplease: to help you create, perfect, and share your ideas about cooking.
		</p>
		<%= link_to('Join Us!', new_user_registration_path, :class => "btn btn-large btn-success") %>
		<%= link_to('Login', new_user_session_path, :class => "btn btn-large btn-primary")%>
		<!-- TODO: Add a continue option for unregistered users. -->
	</div>
</div>